module Minenum
  module Model
    class Reflection
      @owner_class: untyped
      @name: Symbol | String
      @values: Hash[untyped, untyped]
      @adapter: untyped
      @enum_class: Minenum::Enum::Base

      attr_reader adapter_builder: untyped

      def initialize: (untyped, String | Symbol, Hash[untyped, untyped], ?adapter_builder: Minenum::Enum::Adapter::_AdapterBuilder) -> void
      def name: -> Symbol
      def enum_class: -> untyped
      def build_enum: (untyped) -> untyped

      private

      def classify: (String) -> String
    end
  end
end
