module Minenum
  module Enum
    class Base
      extend Forwardable

      @adapter: Minenum::Enum::Adapter::_Adapter

      attr_reader self._values: Minenum::Enum::Values

      alias _inspect inspect

      def self.values: -> Hash[Symbol, untyped]

      def initialize: (untyped) -> void
      def name: -> Symbol?
      def value: -> untyped
      def value=: (untyped) -> untyped

      private

      def _raw_value: -> untyped
    end
  end
end
