module Minenum
  module Model
    interface _Accessor
      def set: (untyped model, String | Symbol name, untyped value) -> untyped
      def get: (untyped model, String | Symbol name) -> untyped
    end

    module InstanceVariableAccessor
      include _Accessor
    end

    module AccessorAdder
      def self?.add: (untyped, Module, Minenum::Model::Reflection) -> void
      def self?.add_singleton_method: (untyped, Minenum::Model::Reflection) -> void
      def self?.add_getter: (Module, Minenum::Model::Reflection) -> void
      def self?.add_setter: (Module, Minenum::Model::Reflection) -> void
    end

    module ClassMethods
      def enum: (String | Symbol name, Hash[String | Symbol, untyped], ?adapter: _Accessor) -> void

      private

      def enum_methods_module: -> Module

      def include: (Module) -> self
    end
  end
end
