module Minenum
  module Model
    module AccessorAdder
      def self?.add: (untyped, untyped, Minenum::Model::Reflection) -> void
      def self?.add_singleton_method: (untyped, Symbol) -> void
      def self?.add_getter: (untyped, Symbol) -> void
      def self?.add_setter: (untyped, Symbol) -> void
    end

    module ClassMethods
      def enum: (String | Symbol name, Hash[String | Symbol, untyped], ?adapter_builder: Minenum::Enum::Adapter::_AdapterBuilder) -> void
      def _minenum_reflections: -> Hash[Symbol, untyped]

      private

      def enum_methods_module: -> Module

      def include: (Module) -> self
    end

    module InstanceMethods
      private

      def _minenum_enum: (Symbol) -> untyped

      def self._minenum_reflections: -> Hash[Symbol, untyped]
    end
  end
end
